#!/bin/ksh
#
# flashrd image configurator
#
# Chris Cappuccio <chris@nmedia.net>

typeset -x TMPDIR

vnddirs="root bin etc sbin usr" # must match vnddirs= in flashrd and stand/rc
device=vnd3
rootvnd=vnd2

set -A part a d e f g h i j k l m n o p


usage() {
 cat <<EOF
Usage: cfgflashrd [-d "dev" | -i "filename"]  [options]

Use one of:
    -d "dev"		Configure an attached disk
    -i "filename"	Configure an image
Options:
    -r "filename"       rdrootfs image (needed only to change ramdisk)
    -e "dir"		directory where elfrdsetroot.c is located (only with -r)
    -c "speed"		set com0 as console at speed "speed"
    -m 			set bsd.mp as primary kernel
    -s 			set bsd.sp as primary kernel
    -t "tzfile"		set timezone using a timezone file fromfrom
			/usr/share/zoneinfo

EOF
}

if [[ "$#" -lt 1 ]]; then
 usage
 exit 1
fi

while :
do
 case $1 in
  -\?)		usage; exit 0;;
  -d|-disk)	t2 "$2"; disk="$2"; shift 2;;
  -i|-image)	t2 "$2"; image="$2"; shift 2;;
  -r|-rdroot)	t2 "$2"; rdfs="$2"; shift 2;;
  -c|-com0)	t2 "$2"; com0="$2"; shift 2;;
  -m|-mp)	t2 "$2"; kernel="bsdmp"; shift;;
  -s|-sp)	t2 "$2"; kernel="bsdsp"; shift;;
  -t|-tz)	t2 "$2"; tzfile="$2"; shift 2;;
  -e)		t2 "$2"; elfrdsetrootdir="$2"; shift 2;;

  --)		shift; break;;
  -*)		usage; exit 1;;
  *)		break;;
 esac
done

# checking arguments

if [[ -n $elfrdsetrootdir && -z $rdfs ]]; then
 echo "Option -e only valid in conjunction with -r"
 exit 1
fi

if [[ -n $disk && -n $image ]]; then
 echo "Choose either -d or -i, not both"
 exit 1
fi

if [[ -z $disk && -z $image ]]; then
 echo "Must choose either -d or -i"
 exit 1
fi

if [[ -n $disk ]]; then
 if [[ ! -b /dev/${disk}a ]]; then
  echo "Device /dev/${disk}a not found"
  exit 1
 fi
 vnd=false
 rootdevice=/dev/${disk}a
fi

if [[ -n $image ]]; then
 if [[ ! -f $image ]]; then
  echo "$flashrd image not found"
  exit 1
 fi
 vnd=true
 rootdevice=/dev/${rootvnd}a
fi

if [[ -n $rdfs && ! -f $rdfs ]]; then
 echo "Sorry rdroot $rdfs not found"
 exit 1
fi

if [[ -n $com0 && ( $com0 -lt 1200 || $com0 -gt 115200 ) ]]; then
 echo "Sorry the com0 speed $com0 is unlikely"
 exit 1
fi

if [[ -n $tzfile ]]; then
 if [[ ! -f $tzfile ]]; then
  tzfile=/usr/share/zoneinfo/$tzfile
 elif [[ ! -f $tzfile ]]; then
  echo "Timezone file not found"
  exit 1
 fi
fi

if [ `id -u` != 0 ]; then
 echo Sorry, mount, vnconfig, and friends require root privileges
 exit 1
fi

if [ -z "$elfrdsetrootdir" ]; then
 elfrdsetrootdir=./elfrdsetroot/
fi

if [ ! -d $elfrdsetrootdir ]; then
 echo % elfrdsetroodir $elfrdsetrootdir not found
fi

vncfgroot() {
 [[ $vnd == true ]] && c 0 vnconfig ${rootvnd} $1
}

vnuncfgroot() {
 [[ $vnd == true ]] && c 0 vnconfig -u ${rootvnd}
}

###
#
# fall back

4() {
 umount -f $tmpmntvnd
}
3() {
 vnconfig -u $device
}
2() {
 umount -f $tmpmnt
}
1() {
 vnuncfgroot
}
0() {
 echo TMPDIR: $TMPDIR
 exit 1
}

. ./flashrd.sub

###
#
# (Re-)Base TMPDIR to a subdiretory of either the current
# TMPDIR value, or to /tmp

TMPDIR=$(c 0 mktemp -t -d cfgflashrd.XXXX)

tmpmnt=$TMPDIR/tmpmnt		# vnd/disk mount point
c 1 mkdir $tmpmnt
tmpmntvnd=$TMPDIR/tmpmntvnd	# openbsd.vnd partition mount point
c 1 mkdir $tmpmntvnd

###
#
# mount vnd or disk

vncfgroot $image

c 1 fsck -p ${rootdevice}

c 1 mount ${rootdevice} $tmpmnt

if [ ! -z "$rdfs" ]; then
 ###
 #
 # compile ELFRDSETROOT

 c 2 cc -o $elfrdsetrootdir/elfrdsetroot $elfrdsetrootdir/elfrdsetroot.c $elfrdsetrootdir/elf32.c $elfrdsetrootdir/elf64.c

 c 2 vnconfig $device $rdfs

 c 3 fsck -p /dev/${device}a

 c 3 mount /dev/${device}a $tmpmntvnd

 cholo=`egrep ^disk= $tmpmntvnd/stand/rc`
 if [ -z "$cholo" ]; then
  echo % no disk= line found in $tmpmntvnd/stand/rc, aborting
  4; 3; 2; 1; 0;
 fi

 ch1=${cholo#disk=}
 if [ ${ch1} != "auto" ]; then
  ch1=${ch1%a}
 fi
 echo Current image device ${ch1}

 getphys()
 {
  read phys?"New physical device name (as seen by destination system)[${ch1}]? "
  if [ -z ${phys} ]; then
   phys=$ch1
  fi
  if [ ! -b /dev/${phys}a -a ${phys} != "auto" ]; then
   echo /dev/${phys}a appear to be nonsense, try again
   getphys
  fi
 }
 getphys
 if [ ${phys} != "auto" ]; then
  phys=${phys}a
 fi

 temp=$(c 4 mktemp -t cfgflashrd.XXXX)
 c 4 "sed -e 's/$cholo/disk=${phys}/' < $tmpmntvnd/stand/rc > $temp"

 c 4 mv $temp $tmpmntvnd/stand/rc

 c 3 umount $tmpmntvnd

 c 2 vnconfig -u $device

 echo Setting ramdisk root image

 for i in bsd bsd.mp bsd.sp; do
  if [ -f $tmpmnt/$i ]; then
   c 2 $elfrdsetrootdir/elfrdsetroot $tmpmnt/$i $rdfs
   cfgbsd=1
  fi
 done
 c 2 rm $elfrdsetrootdir/elfrdsetroot

 if [ -z "$cfgbsd" ]; then
  echo % none of bsd bsd.mp bsd.sp kernel found at flash image.  how odd?
  2; 1; 0;
 fi

 if [ "$kernel" == "bsdsp" ]; then
  if [ -f $tmpmnt/bsd.sp ]; then
   mv $tmpmnt/bsd $tmpmnt/bsd.mp
   mv $tmpmnt/bsd.sp $tmpmnt/bsd
  else
   echo "[bsd.sp not found, primary kernel may already be single processor]"
  fi
 fi

 if [ "$kernel" == "bsdmp" ]; then
  if [ -f $tmpmnt/bsd.mp ]; then
   mv $tmpmnt/bsd $tmpmnt/bsd.sp
   mv $tmpmnt/bsd.mp $tmpmnt/bsd
  else
   echo "[bsd.mp not found, primary kernel may already by multi-processor]"
  fi
 fi

 rm -f $temp
fi

if [ ! -z "$com0" ]; then
 echo Installing boot.conf for com0 at $com0 baud
 mkdir -p $tmpmnt/etc
 cat <<-EOF >$tmpmnt/etc/boot.conf
	stty com0 $com0
	set tty com0
	set timeout 5
	EOF
fi

###
#
# mount running filesystem for other types of changes

c 2 vnconfig $device $tmpmnt/openbsd.vnd

###
#
# map $vnddirs etc to a partition label, mount

x=0
for i in $vnddirs; do
 if [ $i == etc ]; then
  etcpart=${part[$x]}
 fi
 let x=x+1
done

if [ -z "$etcpart" ]; then
 echo "% missing etc in \$vnddirs ($vnddirs) aborting"
 3; 2; 1; 0;
fi

c 3 fsck -p /dev/$device$etcpart

c 3 mount /dev/$device$etcpart $tmpmntvnd

if [ ! -f $tmpmntvnd/.flashrd_version ]; then
 echo % missing etc/.flashrd_version, not flashrd image or \$vnddirs out of sync? what funky?
fi

if [ ! -z "$com0" ]; then
 tmpttys=$TMPDIR/tmpttys
 echo Modifying /etc/ttys for tty00 at $com0 baud
 # Turn off ttyC consoles, turn on com0
 # partially gleaned from install.sub
 sed	-e "/^tty00/s/std.[0-9]*/std.${com0}/"	\
	-e "/^tty00/s/unknown/vt220	/"	\
	-e "/^tty00/s/off.*/on secure/"		\
	-e "/^ttyC/s/on.*secure/off/" $tmpmntvnd/ttys > $tmpttys
 c 4 mv $tmpttys $tmpmntvnd/ttys
fi

###
#
# set hostname

getname()
{
 read hostname?"Hostname: "
 if [ -z "$hostname" ]; then
  echo "Nothing entered? Try again."
  getname
 fi
}

if [ -z "$hostname" ]; then
 echo
 echo Please assign a system hostname...
 getname
fi

echo $hostname > $tmpmntvnd/myname

###
#
# set root password

getpass()
{
 stty -echo
 read pw1?"Password:"
 echo
 read pw2?"Verify:"
 echo
 stty echo

 if [ "$pw1" == "$pw2" ]; then
  password="$pw1"
 fi
 if [ -z "$password" ]; then
  echo "Passwords don't match or password was empty.  Try again."
  getpass
 fi
}

if [ -z "$encpass" ]; then
 if [ -z "$password" ]; then
  echo
  echo Please assign a root password...
  getpass
  echo
 fi
fi

if [ -z "$encpass" ]; then
 encpass=`echo $password | /usr/bin/encrypt -b 8`
fi

tmppass=$TMPDIR/tmppass

echo -n "root:$encpass" > $tmppass

awk -F : '/^root/ \
{ printf(":%s:%s:%s:%s:%s:%s:%s:%s\n", $3, $4, $5, $6, $7, $8, $9, $10) }' \
< $tmpmntvnd/master.passwd >> $tmppass

c 4 "egrep -v '^root:' < $tmpmntvnd/master.passwd >> $tmppass"

c 4 mv $tmppass $tmpmntvnd/master.passwd

c 4 pwd_mkdb -p -d $tmpmntvnd $tmpmntvnd/master.passwd

###
#
# steal ntp servers from local ntpd.conf!

if [ -f $tmpmntvnd/ntpd.conf ]; then
 if [ -z "$ntpervers" ]; then
  ntpservers=`awk ' /^server/ { print $2 } ' /etc/ntpd.conf | tr '\n' ' '`
  read nntpservers?"NTP Servers: [$ntpservers] "
  if [ ! -z "$nntpservers" ]; then
   ntpservers="$nntpservers"
  fi
 fi

 if [ ! -z "$ntpservers" ]; then
  echo Configuring ntpd.conf for NTP servers $ntpservers
   egrep -v ^server $tmpmntvnd/ntpd.conf > $tmppass
   for i in $ntpservers; do
     c 4 "echo servers $i >> $tmppass"
   done
   c 4 mv $tmppass $tmpmntvnd/ntpd.conf
 fi
fi

###
#
# steal dns servers from local resolv.conf!

if [ -z "$dnsservers" ]; then
 dnsservers=`awk ' /^nameserver/ { print $2 } ' /etc/resolv.conf | tr '\n' ' '`
 read ndnsservers?"DNS Servers: [$dnsservers] "
 if [ ! -z "$ndnsservers" ]; then
  dnsservers="$ndnsservers"
 fi
fi

if [ ! -z "$dnsservers" ]; then
 echo Configuring resolv.conf for DNS servers $dnsservers
 c 4 "echo lookup file bind > $tmpmntvnd/resolv.conf"
 for i in $dnsservers; do
  c 4 "echo nameserver $i >> $tmpmntvnd/resolv.conf"
 done
else
 echo Failed to configure nameservers, you must manually configure /etc/resolv.conf
fi

###
#
# tzfile

if [ ! -z "$tzfile" -a -f "$tzfile" ]; then
 c 4 rm $tmpmntvnd/localtime
 c 4 cp $tzfile $tmpmntvnd/localtime
fi

###
#
# this is the end

c 3 umount $tmpmntvnd

###
#
# done with the main disk vnd

c 2 vnconfig -u $device

c 1 umount $tmpmnt

###
#
# done with flash img vnd

vnuncfgroot

rm -r $TMPDIR

echo Done
