#!/bin/ksh
#
# mkboot
#
# Chris Cappuccio <chris@nmedia.net>

date=`date +%Y%m%d`
arch=`uname -m`

[ -z "$distloc" ] && distloc=/

[ -z "$rootdevice" ] && rootdevice=vnd3

[ -z "$totalsize" ] && totalsize=1951488

[ -z "$bytessec" ] && bytessec=512

[ -z "$dest" ] && dest=flashimg.$arch-$date

vncfgroot() {
 [[ $vnd == true ]] && c 0 vnconfig $rootdevice $1
}

vnuncfgroot() {
 [[ $vnd == true ]] && c 0 vnconfig -u $rootdevice
}

###
#
# fall back

2() {
 umount -f /dev/"$rootdevice"a
}
1() {
 vnuncfgroot
}
0() {
 exit 1
}

. ./flashrd.sub

[ -z "$tmpmnt" ] && tmpmnt=$(c 0 mktemp -t -d mkboot.XXXXXX)

###
#
# Create boot image

tmplabel=$(c 0 mktemp -t mkbootlabel.XXXXXX)

if [[ $vnd == true ]]; then

 # Create vnd image, must zero out the first few sectors or else disklabel freaks out...
 c 0 "dd if=/dev/zero bs=$bytessec count=$bytessec of=$dest > $TMPDIR/last.output 2>&1"
 vncfgroot $dest
 cylinders=$((totalsize / 64))
 trackscylinder=1
 sectorstrack=64
 c 1 "fdisk -l $totalsize -f $distloc/usr/mdec/mbr -yi $rootdevice > $TMPDIR/last.output 2>&1"
 c 1 disklabel $rootdevice > $tmplabel
 sectorscylinder=$((totalsize / cylinders))

else

 # Disk specified, use default kernel geometry
 c 0 "fdisk -f $distloc/usr/mdec/mbr -yi $rootdevice > $TMPDIR/last.output 2>&1"
 c 0 disklabel $rootdevice > $tmplabel
 totalsize=`awk -F: ' /^total sectors:/ {print $2} ' $tmplabel`
 bytessec=`awk -F: ' /^bytes\/sector:/ {print $2} ' $tmplabel`
 sectorstrack=`awk -F: ' /^sectors\/track:/ {print $2} ' $tmplabel`
 sectorscylinder=`awk -F: ' /^sectors\/cylinder:/ {print $2} ' $tmplabel`
 trackscylinder=`awk -F: ' /^tracks\/cylinder:/ {print $2} ' $tmplabel`
 cylinders=`awk -F: ' /^cylinders:/ {print $2} ' $tmplabel`
fi

totalmbytes=$((((totalsize / 1024) * bytessec) / 1024))
echo -n "Disk size ${totalmbytes}MB ($totalsize sectors"
if [ "$bytessec" == "512" ]; then
 echo ")"
else
 echo ", $bytessec bytes/sector)"
fi

# Main partition comprises the total disk, minus first sector
offset=64
asize=$((totalsize - offset))

cat > $tmplabel <<-EOF
	type: ESDI
	bytes/sector: $bytessec
	sectors/track: $sectorstrack
	tracks/cylinder: $trackscylinder
	sectors/cylinder: $sectorscylinder
	cylinders: $cylinders
	total sectors: $totalsize

	a: $asize   $offset   4.2BSD  $((bytessec * 2))  $((bytessec * 16))  1
	c: $totalsize 0 unused 0 0
	EOF

c 1 disklabel -R $rootdevice $tmplabel

echo -n Creating filesystem on /dev/r${rootdevice}a
c 1 "newfs -S $bytessec /dev/r${rootdevice}a > $TMPDIR/last.output 2>&1"
echo

c 1 mount /dev/${rootdevice}a $tmpmnt

echo Installing bootblocks

c 2 "installboot -r $tmpmnt $rootdevice $distloc/usr/mdec/biosboot $distloc/usr/mdec/boot > $TMPDIR/last.output 2>&1"

c 2 mkdir $tmpmnt/new $tmpmnt/old $tmpmnt/etc

echo Generate initial random seed

c 2 "dd if=/dev/random of=$tmpmnt/etc/random.seed bs=512 count=1 > $TMPDIR/last.output 2>&1"
c 2 "chmod 600 $tmpmnt/etc/random.seed"

umountwait 1 $tmpmnt

vnuncfgroot

exit 0
