#!/bin/ksh
#
# mkboot
#
# Chris Cappuccio <chris@nmedia.net>

date=`date +%Y%m%d`
arch=`uname -m`

if [ -z "$rootdevice" ]; then
 export rootdevice=svnd3
fi

if [ -z "$count" ]; then
 export count=1024
fi

if [ -z "$bsize" ]; then
 export bsize=1m
fi

if [ -z "$dest" ]; then
 dest=flashimg.$arch-$date
fi

if [ -z "$tmpmnt" ]; then
 tmpmnt=`mktemp -d /tmp/mkboot.XXXXXXXX`
fi

vncfgroot() {
 [ -z "$novnd" ] && c 0 vnconfig $rootdevice $1
}      

vnuncfgroot() {
 [ -z "$novnd" ] && c 0 vnconfig -u $rootdevice
}

###
#
# fall back

2() {
 umount /dev/"$rootdevice"a
}
1() {
 vnuncfgroot
}
0() {
 exit 1
}

. ./flashrd.sub

###
#
# Create boot image

tmplabel=`mktemp /tmp/mkbootlabel.XXXXXXXX`

if [ -z "$novnd" ]; then
 echo -n "Creating base image ($bsize*$count)"

 c 0 "dd if=/dev/zero of=$dest bs=$bsize count=$count >/dev/null 2>&1"
 echo
fi

c 0 vncfgroot $dest

c 1 "fdisk -yi $rootdevice >/dev/null 2>&1"

c 1 "disklabel $rootdevice | egrep -v ^type: > $tmplabel"

totalsize=`awk -F: ' /^total sectors:/ {print $2} ' $tmplabel`
sectorstrack=`awk -F: ' /^sectors\/track:/ {print $2} ' $tmplabel`

asize=$((totalsize - sectorstrack))

cat >>$tmplabel <<-EOF
	type: ESDI
	
	a: $asize   $sectorstrack   4.2BSD  1024    8192    16
	EOF

c 1 "disklabel -R $rootdevice $tmplabel >/dev/null 2>&1"

echo -n Creating filesystem on /dev/r${rootdevice}a
c 1 "newfs /dev/r${rootdevice}a >/dev/null 2>&1"
echo

c 1 mount /dev/${rootdevice}a $tmpmnt

echo Installing bootblocks

c 2 cp $distloc/usr/mdec/boot $tmpmnt/boot

c 2 "$distloc/usr/mdec/installboot $tmpmnt/boot $distloc/usr/mdec/biosboot $rootdevice >/dev/null 2>&1"

c 2 mkdir $tmpmnt/new $tmpmnt/old

c 1 umount $tmpmnt

vnuncfgroot
