#!/bin/ksh
#
# mkboot
#
# Chris Cappuccio <chris@nmedia.net>

date=`date +%Y%m%d`
arch=`uname -m`

if [ -z "$rootdevice" ]; then
 export rootdevice=svnd3
fi

if [ -z "$count" ]; then
 export count=1024
fi

if [ -z "$bsize" ]; then
 export bsize=1m
fi

if [ -z "$dest" ]; then
 dest=flashimg.$arch-$date
fi

if [ -z "$tmpmnt" ]; then
 tmpmnt=`mktemp -d /tmp/mkboot.XXXXXXXX`
fi

vncfgroot() {
 if [ -z "$novnd" ]; then
  if ! vnconfig $rootdevice $1; then
   echo % vnconfig $rootdevice $1 failure
   exit 1
  fi
 fi
}      

vnuncfgroot() {
 if [ -z "$novnd" ]; then
  if ! vnconfig -u $rootdevice; then
   echo % vnconfig -u $rootdevice failure
   exit 1
  fi
 fi
}

###
#
# Create boot image

tmplabel=`mktemp /tmp/mkbootlabel.XXXXXXXX`

if [ -z "$novnd" ]; then
 echo -n "Creating base image ($bsize*$count)"

 if ! dd if=/dev/zero of=$dest bs=$bsize count=$count >/dev/null 2>&1; then
  echo % dd if=/dev/zero of=$dest bs=$bsize count=$count failure
  exit 1
 fi
 echo
fi

vncfgroot $dest

if ! fdisk -yi $rootdevice >/dev/null 2>&1; then
 echo % fdisk -yi $rootdevice
 vnuncfgroot
 exit 1
fi

if ! disklabel $rootdevice | egrep -v ^type: > $tmplabel; then
 echo % disklabel $rootdevice > $tmplabel failure
 vnuncfgroot
 exit 1
fi

totalsize=`awk -F: ' /^total sectors:/ {print $2} ' $tmplabel`
sectorstrack=`awk -F: ' /^sectors\/track:/ {print $2} ' $tmplabel`

asize=$((totalsize - sectorstrack))

cat >>$tmplabel <<-EOF
	type: ESDI
	
	a: $asize   $sectorstrack   4.2BSD  1024    8192    16
	EOF

if ! disklabel -R $rootdevice $tmplabel >/dev/null 2>&1; then
 echo % disklabel -R $rootdevice $tmplabel failure
 vnuncfgroot
 exit 1
fi

echo -n Creating filesystem on /dev/r"$rootdevice"a
if ! newfs /dev/r"$rootdevice"a >/dev/null 2>&1; then
 echo % newfs /dev/r"$rootdevice"a failure
 vnuncfgroot
 exit 1
fi
echo

if ! mount /dev/"$rootdevice"a $tmpmnt; then
 echo % mount /dev/"$rootdevice"a $tmpmnt failure
 vnuncfgroot
 exit 1
fi

echo Installing bootblocks

if ! cp $distloc/usr/mdec/boot $tmpmnt/boot; then
 echo % cp $distloc/usr/mdec/boot $tmpmnt/boot
 umount /dev/"$rootdevice"a
 vnuncfgroot
 exit 1
fi

if ! $distloc/usr/mdec/installboot $tmpmnt/boot $distloc/usr/mdec/biosboot $rootdevice >/dev/null 2>&1; then
 echo % $distloc/usr/mdec/installboot $tmpmnt/boot $distloc/usr/mdec/biosboot $rootdevice failure
 umount /dev/"$rootdevice"a
 vnuncfgroot
 exit 1
fi

if ! mkdir $tmpmnt/new $tmpmnt/old; then
 echo % mkdir $tmpmnt/new $tmpmnt/old failure
 umount /dev/"$rootdevice"a
 vnuncfgroot
 exit 1
fi

if ! umount $tmpmnt; then
 echo % umount $tmpmnt failure
fi

vnuncfgroot
