#!/bin/ksh
#
# flashrd mkkern
#
# create luscious ramdisk version of GENERIC
#
# Chris Cappuccio <chris@nmedia.net>
#

if [ -z "$tmpmnt" ]; then
 tmpmnt=`mktemp -d /tmp/mkkern.XXXXXXXX`
fi

###
#
# blocks

if [ -z "$blocks" ]; then
 blocks=6080
fi

###
#
# rdrootfs

if [ -z "$szezroot" -a -z "$1" ]; then
 echo "% mkkern <$blocks rdrootfs>"
 exit 1
fi

if [ -z "$szezroot" ]; then
 szezroot=$1
fi

if [ ! -f $szezroot ]; then
 echo % $szezroot is not a file
 exit 1
fi

###
#
# kernel source

if [ -z "$kernsrc" ]; then
 kernsrc=/usr/src/sys/arch/`uname -m`
fi

if [ ! -d $kernsrc ]; then
 echo % $kernsrc not found
 exit 1
fi

###
#
# elfrdsetroot

if [ -z "$elfrdsetroot" ]; then
 elfrdsetroot=/usr/src/distrib/common/elfrdsetroot.c
fi

if [ ! -f $elfrdsetroot ]; then
 echo % $elfrdsetroot not found
 exit 1
fi

###
#
# GENERIC config

if [ ! -f $kernsrc/conf/GENERIC ]; then
 echo % $kernsrc/conf/GENERIC config not found
 exit 1
fi

. ./flashrd.sub

###
#
# modify GENERIC

egrep -v ^config < $kernsrc/conf/GENERIC >$kernsrc/conf/FLASHRD

cat >> $kernsrc/conf/FLASHRD <<-EOF
	option	RAMDISK_HOOKS
	option	MINIROOTSIZE=$blocks
	config	bsd	root on rd0a swap on rd0b and wd0b and sd0b
	pseudo-device	rd 1
	EOF

sed -e 's/GENERIC/FLASHRD/' < $kernsrc/conf/GENERIC.MP > $kernsrc/conf/FLASHRD.MP

###
#
# compile ELFRDSETROOT first (so we can bail out if it fails without waiting for GENERIC)

c 0 cc -o ./elfrdsetroot $elfrdsetroot

###
#
# compile our version of GENERIC

echo -n Configuring FLASHRD kernel
wd=`pwd`
cd $kernsrc/conf
c 0 "config FLASHRD >/dev/null 2>&1"
c 0 "config FLASHRD.MP >/dev/null 2>&1"
echo

echo -n Compiling FLASHRD kernel
cd $kernsrc/compile/FLASHRD
c 0 "make depend >/dev/null 2>&1"
c 0 "make >/dev/null 2>&1"
c 0 cp bsd $tmpmnt/bsd
echo

echo -n Compiling FLASHRD.MP kernel
cd $kernsrc/compile/FLASHRD.MP
c 0 "make depend >/dev/null 2>&1"
c 0 "make >/dev/null 2>&1"
c 0 cp bsd $tmpmnt/bsd.mp
echo

###
#
# run elfrdsetroot

cd $wd
c 0 ./elfrdsetroot $tmpmnt/bsd $szezroot
c 0 ./elfrdsetroot $tmpmnt/bsd.mp $szezroot
