#!/bin/ksh
#
# flashrd mkrdroot
#
# create the kernel ramdisk
#
# this environment (and custom rc) is for setting up vnds
# so that we can mount the system and pass to real /etc/rc
#
# Chris Cappuccio <chris@nmedia.net>
#

# Crunchgen links
#

[ -z "$progs" ] && progs="ksh pax ls fsck fsck_ffs reboot init mount mount_ffs mount_vnd umount cp mv"

[ -z "$standlink" ] && standlink="tar pax mount_vnd vnconfig umount"

[ -z "$binlink" ] && binlink="sh ksh ls cp mv"

[ -z "$sbinlink" ] && sbinlink="init mount mount_ffs fsck fsck_ffs reboot"

# Files to copy
#

[ -z "$etccopy" ] && etccopy="etc/login.conf etc/pwd.db"

###
#
# blocks

[ -z "$blocks" ] && blocks=4600

###
#
# rdrootfs, device, distloc

[ -z "$rdroot" ] && rdroot=rd.`uname -m`-`date +%Y%m%d`

[ -z "$device" ] && device=vnd0

if [ -z "$distloc" -a -z "$1" ]; then
 echo "% mkrdroot <openbsd base>"
 exit 1
fi

[ -z "$distloc" ] && distloc=$1

###
#
# fall back

2() {
 umount -f $tmpmntdir
}
1() {
 vnconfig -u $device
}
0() {
 exit 1
}

. ./flashrd.sub

if [ ! -f $distloc/dev/MAKEDEV ]; then
 echo % $distloc/dev/MAKEDEV not found
 exit 1
fi

if [ ! -f /usr/src/bin/Makefile ]; then
 echo OpenBSD source tree not found at /usr/src/bin
 echo Giving up...
 exit 1
fi
if [ ! -f /usr/src/sbin/Makefile ]; then
 echo OpenBSD source tree not found at /usr/src/sbin
 echo Giving up...
 exit 1
fi

echo Creating ramdisk rootfs

###
#
# dd, vnconfig, disklabel, newfs

c 0 "dd if=/dev/zero of=$rdroot bs=512 count=$blocks >/dev/null 2>&1"

c 0 vnconfig $device $rdroot

tmplabel=`mktemp -t mkrdrootlabel.XXXXXXXXX`
tmpmntdir=`mktemp -t -d mkrdroot.XXXXXXXXX`

c 1 "disklabel $device > $tmplabel 2>/dev/null"

totalsize=`awk -F: ' /^total sectors:/ {print $2} ' $tmplabel`
cat >>$tmplabel <<-EOF
	a: $totalsize   0   4.2BSD  1024    8192    16
	EOF

c 1 "disklabel -R $device $tmplabel >/dev/null 2>&1"

c 1 "newfs -m 0 -o space -i 1024 /dev/r${device}a >/dev/null 2>&1"

c 1 mount /dev/${device}a $tmpmntdir

###
#
# Our ramdisk base

c 2 mkdir $tmpmntdir/bin $tmpmntdir/dev $tmpmntdir/etc $tmpmntdir/etc/firmware $tmpmntdir/home $tmpmntdir/mnt $tmpmntdir/root $tmpmntdir/sbin $tmpmntdir/stand $tmpmntdir/sys $tmpmntdir/tmp $tmpmntdir/usr $tmpmntdir/var $tmpmntdir/flash

# mount_mfs preserves permissions from parent mount
c 2 chmod 1777 $tmpmntdir/tmp

c 2 cp $distloc/.cshrc $distloc/.profile $tmpmntdir

c 2 cp $distloc/dev/MAKEDEV $tmpmntdir/dev

###
#
# Devices with an extra touch of bpf (normal distribution has bpf0-bpf9, so create starting at bpf10)

wd=`pwd`
cd $tmpmntdir/dev
c 2 ./MAKEDEV all

i=10
while [ $i -le 511 ]; do
 c 2 ./MAKEDEV bpf$i
 let i=i+1
done
cd $wd

###
#
# Oppa Crunchgen Style

echo -n "Crunchgen ($progs)"
cgdir=`mktemp -t -d mkrdrootcg.XXXXXXXXX`
cat  <<-_EOF >>$cgdir/kcopy.conf
srcdirs /usr/src/bin /usr/src/sbin

progs $progs
ln ksh -sh       # init invokes the shell with "-sh" in argv[0]
ln ksh sh
ln pax tar
ln mount_vnd vnconfig

libs -lutil
	_EOF

c 2 cd $cgdir
c 2 "crunchgen -Em Makefile $cgdir/kcopy.conf >/dev/null 2>&1"
c 2 "make objs >/dev/null 2>&1"
c 2 "make >/dev/null 2>&1"
c 2 cd $wd
echo

###
#
# Copy specific items to kernel ramdisk

echo -n Linking kcopy

c 2 cp $cgdir/kcopy $tmpmntdir/stand/kcopy
c 2 rm -r $cgdir
for i in $standlink; do
 echo -n " stand/$i"
 c 2 ln $tmpmntdir/stand/kcopy $tmpmntdir/stand/$i
done
for i in $binlink; do
 echo -n " bin/$i"
 c 2 ln $tmpmntdir/stand/kcopy $tmpmntdir/bin/$i
done
for i in $sbinlink; do
 echo -n " sbin/$i"
 c 2 ln $tmpmntdir/stand/kcopy $tmpmntdir/sbin/$i
done
echo
echo -n Copying
for i in $etccopy; do
 echo -n " $i"
 c 2 cp $distloc/$i $tmpmntdir/etc
done
echo

echo -n Copying pre-mount firmware to ramdisk rootfs
if [ -f firmware.list ]; then
 while read line; do

  line=${line%%#*}		# strip comments
  test -z "$line" && continue

  echo -n " $line"
  c 2 cp $distloc/etc/firmware/$line $tmpmntdir/etc/firmware
 done < firmware.list
else
 echo -n " (no firmware.list found for ramdisk firmware copy)"
fi

echo

###
#
# Copy custom rc to kernel ramdisk, cleanup

c 2 cp etc/rc $tmpmntdir/etc/rc

c 2 cp stand/rc $tmpmntdir/stand/rc

umountwait 1 $tmpmntdir

c 0 vnconfig -u $device
